### ISSUE TITLE
Container image

### ISSUE THREAD

**Issue by kfox1111** [spiffe/spiffe-helper#107]
There needs to be a container image for this so it can be more easily used in containerized environments.

**Comment by faisal-memon** [comment]
Thats a good idea.

**Comment by kfox1111** [comment]
Once there is an official spiffe-helper:0.8.0 image?

**Comment by faisal-memon** [comment]
Multi arch [spiffe-helper:0.8.0](https://github.com/spiffe/spiffe-helper/pkgs/container/spiffe-helper/272259699?tag=0.8.0) image is now available.
