### ISSUE TITLE
Add ability to exit on successful retrieval of JWT SVID

### ISSUE THREAD

**Issue by keeganwitt** [spiffe/spiffe-helper#121]

**Comment by kfox1111** [comment]
It also can not run a command on exit near as I can tell. The code should probably call the same function that does cmd execution and signaling as well as exit?

**Comment by keeganwitt** [comment]
> It also can not run a command on exit near as I can tell. The code should probably call the same function that does cmd execution and signaling as well as exit?

Yes, I think so. It's confusing that there's not parity here.

**Comment by keeganwitt** [comment]
Actually signaling might be confusing since if there's multiple JWTs, it would signal multiple times.

**Comment by kfox1111** [comment]
> Actually signaling might be confusing since if there's multiple JWTs, it would signal multiple times.

The same is true on exiting? With multiple jwts I'd think the exit should happen when all have been fetched. Probably signaling, and cmd should happen the same way? But that is more tricky...

**Comment by keeganwitt** [comment]
> The same is true on exiting? With multiple jwts I'd think the exit should happen when all have been fetched. Probably signaling, and cmd should happen the same way? But that is more tricky...

Yea, I guess it should signal once when all the JWTs are fetched, not each time. Dunno why I didn't think of that.

**Comment by faisal-memon** [comment]
@keeganwitt This should be met with the [daemon-mode setting](https://github.com/spiffe/spiffe-helper/pull/161) released in 0.8.0. Can you confirm?

**Comment by keeganwitt** [comment]
> @keeganwitt This should be met with the [daemon-mode setting](https://github.com/spiffe/spiffe-helper/pull/161) released in 0.8.0. Can you confirm?

Yes, this is the case.
