### ISSUE TITLE
SPIFFE Helper releases

### ISSUE THREAD

**Issue by MarcosDY** [spiffe/spiffe-helper#165]
Add automation to create images when releasing spiffe-helper,

Acceptance criteria:
- use scratch image as base
- images are pushed into `ghcr.io`

Optional:
- Release windows images

**Comment by gflarity** [comment]
Not sure how this typically managed, but seems like it should be possible: 
1) trigger a github workflow when there's a new tag. Say of the format v#.#.# (like v1.0.0)
2) create a new release via a github workflow: https://trstringer.com/github-actions-create-release-upload-artifacts/

I'll investigate further (see how it's done in other spiffe projects) and submit a PR if a maintainer can give the nod that it's likely to be accepted.

**Comment by gflarity** [comment]
> Isn't there already a workflow that matches the spire-controller-manager (https://github.com/spiffe/spiffe-helper/blob/main/.github/workflows/release_build.yaml matching https://github.com/spiffe/spire-controller-manager/blob/main/.github/workflows/release_build.yaml)?

I'll take a look. Who's the current maintainer who would actually create a release?

**Comment by keeganwitt** [comment]
I can't see the member list, but I'd start with @faisal-memon. I think he did the last release.

**Comment by faisal-memon** [comment]
@MarcosDY Docker containers are now published with distroless as base. Is it ok to close this as completed and track windows builds with a separate issue?

**Comment by MarcosDY** [comment]
Looks good to me, plz go ahead and create another issue for windows and close this,

Thanks!!!

**Comment by kfox1111** [comment]
images being binaries? Not sure we can distribute windows based containers?

**Comment by faisal-memon** [comment]
Tracking windows builds via #215

**Comment by kfox1111** [comment]
I think we may be able to hit both the arm and windows build case with goreleaser

https://github.com/spiffe/k8s-spiffe-workload-auth-config/blob/main/.github/workflows/release.yaml
https://github.com/spiffe/k8s-spiffe-workload-auth-config/blob/main/.goreleaser.yaml
