### ISSUE TITLE
Re-name this project as `spiffe-helper`

### ISSUE THREAD

**Issue by ajessup** [spiffe/spiffe-helper#2]
This tool describes itself as the "SPIRE" sidecar, but wouldn't it work with any platform that implements the SPIFFE API? If so the project description and documentation should be updated accordingly.

**Comment by evan2645** [comment]
IMO, the name "sidecar" is misleading for the reason you point out and others. We would probably do well to rename this project entirely. Something along the lines of `spiffe-helper` makes good sense.

**Comment by jainvipin** [comment]
I understand the confusion. However, for the use cases of k8s, `sidecar` is a good name for what it does.  May be `spiffe-consort`?

**Comment by ajessup** [comment]
Fixed in #4
