### ISSUE TITLE
Why EC certs and not RSA?

### ISSUE THREAD

**Issue by blaggacao** [spiffe/spiffe-helper#26]
I'm just relaying the question while I was investigating into the direction of getting EC cert support to the fundamental rust ssl libraries, I can't give a solid answer myself:

https://github.com/ctz/rustls/pull/409#issuecomment-720709802

**Comment by briansmith** [comment]
My question there isn't "why use EC certs instead of RSA" but rather "Why use a non-standard format instead of a standard format?" PKCS#8 isn't great but it is much more universally supported.

**Comment by blaggacao** [comment]
Oh thanks! I felt the need for making the title more palpable, but that came at the expense of accuracy.

**Comment by blaggacao** [comment]
@briansmith It doesn't seem there is emerging a compelling answer to your question, so I'm closing this.
