### ISSUE TITLE
Update configuration file to snake case

### ISSUE THREAD

**Issue by MarcosDY** [spiffe/spiffe-helper#33]
Config file is using camel case, but in spire we are using snake case,
We may update it to snake format to be consistent

**Comment by MarcosDY** [comment]
It is important to keep compatibility for a couple versions

**Comment by FedeNQ** [comment]
Can you assign it to me?

**Comment by faisal-memon** [comment]
Resolved via https://github.com/spiffe/spiffe-helper/pull/77
