### ISSUE TITLE
Update helper to use the new workload API

### ISSUE THREAD

**Issue by drrt** [spiffe/spiffe-helper#5]

**Comment by omerlh** [comment]
The new API also supports JWT tokens, correct?

**Comment by faisal-memon** [comment]
I took a first pass at this but I had to use a global variable because I couldn't find a way to push the sidecar object through the new watcher interface. Does anyone know a better way? 

My changes (not PR worthy): https://github.com/faisal-memon/spiffe-helper/commit/80513be8775579fadc65aabbe92ad3259a5b2654

**Comment by azdagron** [comment]
I've added comment to your commit with one solution.

Also, just a note, we're actively developing a v2 version of the go-spiffe library that should be ready in a few short weeks (hopefully sooner). We'll probably want to move to the v2 library when it comes out.

**Comment by faisal-memon** [comment]
Thanks for the feedback. Ill wait for the v2 library before continuing work on this.

**Comment by azdagron** [comment]
Cool. I appreciate you working on this, @faisal-memon!

**Comment by blaggacao** [comment]
Maybe out of scope: It would be nice to provide cli overrides which are passed to the `cmdArgs`.

In that way, when working with docker, I don't need an alternative helper.conf just to pass a debug flag around.

`spiffe-helper -- -d 5`

**Comment by faisal-memon** [comment]
I was able to update this to use the v2 api. PR: https://github.com/spiffe/spiffe-helper/pull/25

**Comment by faisal-memon** [comment]
Any interest in this PR?

**Comment by faisal-memon** [comment]
Resolved via https://github.com/spiffe/spiffe-helper/pull/25
